pipeline {
    agent any
    tools {
        maven 'Maven 3.5.0'
        jdk 'OpenJDK 13'
    }
    stages {
            stage('checkout') {
                steps {
                    script {
                        def scmVars = checkout([$class: 'GitSCM', branches: [[name: 'master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanCheckout']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Corilus/kafdrop.git']]])
                    }
                }
            }
            stage('build') {
                steps {
                    sh "mvn -B clean integration-test package assembly:single docker:build"
                    sh "docker push quay.io/corilus/kafdrop:latest"
                }
            }
    }
}
